### ISSUE TITLE
defaultProps

### ISSUE THREAD

**Issue by felipemfp** [rafaelcorreiapoli/react-metodologia#1]
![image](https://cloud.githubusercontent.com/assets/8146112/26050763/3f92508a-3936-11e7-991d-4a11228fd1f1.png)

Não deveria ser(?):

```javascript
SearchInput.defaultProps = {
  resultsCount: 0
}
```

**Comment by rafaelcorreiapoli** [comment]
Muito obrigado! vou corrigir

**Comment by rafaelcorreiapoli** [comment]
2908bd07c94340d467d160f0e804851406196c7c
